### ISSUE TITLE
What is the ssh username and password on the RPI images?

### ISSUE THREAD

**Issue by JanezCim** [ex-zee-ex/phosphorm#1]
Hey, great project, I'm trying to customise the MIDI input to some of my devices, can you give us the pass and username you are using for your beta images?

**Comment by ex-zee-ex** [comment]
i never did any ssh in this process, pretty sure everything is either
default or passwords set to 'password'

**Comment by JanezCim** [comment]
Yes, solved, the password is "password" :)
