### ISSUE TITLE
Cant get the shader_phospor to work

### ISSUE THREAD

**Issue by JanezCim** [ex-zee-ex/phosphorm#3]
Im trying to get the phospor_shader to work on Ubuntu 18.04 instead i can only get the white circle to show

when I run the program out of the box i see a white circle and hear a sound (i think this is how it sould be):

![image](https://user-images.githubusercontent.com/8426792/103347588-ad1fed80-4a97-11eb-9f4c-1da715f778d5.png)

But when i edit the main.cpp to look like this (my understanding is that this should enable the green shader)
```
int main(){
	ofGLWindowSettings settings;
	settings.setGLVersion(3,2);


	// ofGLESWindowSettings settings;
	// settings.glesVersion=2;
	settings.setSize(720,480);
	ofCreateWindow(settings);
    
	// this kicks off the running of my app
	// can be OF_WINDOW or OF_FULLSCREEN
	// pass in width and height too:
	ofRunApp(new ofApp());
}
```

I get a completely white screen and error message that looks like this:
![image](https://user-images.githubusercontent.com/8426792/103347492-70ec8d00-4a97-11eb-9360-d4814217f7bd.png)

When i delete the `precision highp float;` inside `shader_phospor.frag` like suggested in https://github.com/pxscene/pxCore2/issues/679 the error dissapears but i only see the white circle again.

**Comment by ex-zee-ex** [comment]
if yr running on ubuntu vs raspbian you'll need to use a different kind of
shader.  rpis run esgl (short for embedded systems gl, this is the shader
language for browsers, smart phones, chromebooks, etc etc).  desktops work
with opengl, check the examples in the shader folder of openFrameworks for
to to modify the esgl to run on regular sized gl, its just some mild syntax
diffences (no specificitions of precision in particular)

**Comment by JanezCim** [comment]
You are right, also to add it seems like there are also GL differences between RPI3 and RPI4. Anyway closing this since I got my answer
